banco/urls.py
from django.urls import path
from .views import *
app_name = 'banco'
urlpatterns = [
    path('g-cotacao/', get_cotacao, name='get_cotacao'),
    path('c-conta_bancaria/',create_conta_bancaria, name='create_conta_bancaria' ),
    path('c-user/',create_user, name='create_user'),
    path('g-conta_bancaria/<int:pessoa_id>/', get_conta_bancaria, name = 'get_conta_bancaria'),
    path('d-conta_bancaria/<int:pessoa_id>/', delete_conta_bancaria, name = 'delete_conta_bancaria'),
    path('u-conta_bancaria/<int:pessoa_id>/', update_conta_bancaria, name = 'update_conta_bancaria'),
    path('',pagina_inicial, name= 'pagina_inicial')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('banco.urls'))
]

banco/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Cotacao(models.Model):
    moeda_1 = models.CharField(max_length=3)
    moeda_2 = models.CharField(max_length=3)
    conversao = models.CharField(max_length=100, blank=True, null=True)
    valor_venda = models.FloatField(blank=True, null=True)
    valor_compra = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f'{self.conversao}'
    

class ContaBancaria(models.Model):
    saldo_BLR = models.FloatField(blank=True, null=True)
    saldo_USD = models.FloatField(blank=True, null=True)
    saldo_EUR = models.FloatField(blank=True, null=True)
    saldo_BTC = models.FloatField(blank=True, null=True)
    saldo_ARS = models.FloatField(blank=True, null=True)
    pessoa = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

banco/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class CotacaoForm(forms.ModelForm):
    class Meta:
        model = Cotacao
        fields = ['moeda_1','moeda_2'] 

class ContaBancariaForm(forms.ModelForm):
    class Meta:
        model = ContaBancaria
        fields = [
    'saldo_BLR', 
    'saldo_USD',
    'saldo_EUR',
    'saldo_BTC',
    'saldo_ARS',
    'pessoa',
]
        
class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',]

banco/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
import requests
from django.urls import reverse
# Create your views here.

def get_cotacao(request):
    form = CotacaoForm(request.GET or None)
    moeda_1 = None
    moeda_2 = None
    cotacao = None
    if form.is_valid():
        moeda_1 = form.cleaned_data['moeda_1']
        moeda_2 = form.cleaned_data['moeda_2']

        response = requests.get(f'https://economia.awesomeapi.com.br/json/last/{moeda_1}-{moeda_2}')

        if response.status_code == 200:
            dados_api = response.json()
            dados_api = dados_api[f'{moeda_1}{moeda_2}'] #A api externa funciona com um dicionário dentro de outro, entao tenho que acessar chave e valor duas veses
            cotacao = Cotacao.objects.create(
                moeda_1 = moeda_1,
                moeda_2 = moeda_2,
                conversao = dados_api.get('name'),
                valor_venda = dados_api.get('bid'),
                valor_compra = dados_api.get('ask'),
            )
    return render(request, 'banco_g-cotacao.html', {'form':form, 'cotacao':cotacao})

def create_conta_bancaria(request):
    form = ContaBancariaForm()
    if request.method == 'POST':
        form = ContaBancariaForm(request.POST)

        if form.is_valid():
            pessoa = form.save()
            return redirect('banco:get_conta_bancaria', pessoa_id = pessoa.pk)
    return render(request, 'banco_c-conta_bancaria.html', {'form':form})

def create_user(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('banco:create_conta_bancaria')
    return render(request, 'banco_c-user.html', {'form':form})


def get_conta_bancaria(request, pessoa_id):
    try:
        usuario = ContaBancaria.objects.get(pk = pessoa_id)
        return render(request, 'banco_g-conta_bancaria.html', {'usuario':usuario})
    except ContaBancaria.DoesNotExist:
        return redirect('banco:create_conta_bancaria')
 
def delete_conta_bancaria(request, pessoa_id):
    usuario = ContaBancaria.objects.get(pk = pessoa_id)
    usuario.delete()
    return redirect('banco:pagina_inicial')

def update_conta_bancaria(request, pessoa_id):
    usuario = ContaBancaria.objects.get(pk = pessoa_id)
    form_action = reverse('banco:update_conta_bancaria', args=(pessoa_id,))

    form = ContaBancariaForm()
    if request.method == 'POST':
        form = ContaBancariaForm(request.POST, instance=usuario)
        if form.is_valid():
            pessoa = form.save()
            return redirect('banco:get_conta_bancaria', pessoa_id = pessoa.pk)
        
    return render(request, 'banco_u-conta_bancaria.html', {'form_action':form_action, 'form':ContaBancariaForm(instance=usuario) })

def pagina_inicial(request):
    return render(request, 'pagina_inicial.html',)

banco/templates/banco_c-conta_bancaria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação de Conta Bancária</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card mt-5 shadow-sm">
                    <div class="card-header text-center bg-success text-white">
                        <h2>Criação de Conta Bancária</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ form_action }}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success w-100">Criar Conta Bancária</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

banco/templates/banco_c-user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação de Usuário</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card mt-5 shadow-sm">
                    <div class="card-header text-center bg-primary text-white">
                        <h2>Criação de Usuário</h2>
                    </div>
                    <div class="card-body">
                        <form 
                            action="{{ form_action }}"
                            method="POST"
                            enctype="multipart/form-data"
                            class="needs-validation"
                            novalidate
                        >
                            {% csrf_token %}
                            {% for field in form %}
                                {% if forloop.counter != 4 %}
                                    <div class="mb-3">
                                        {{ field.label_tag }} 
                                        {{ field }}
                                        {% if field.errors %}
                                            <div class="text-danger">
                                                {{ field.errors }}
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            {% endfor %}

                            {% if form.non_field_errors %}
                                <div class="alert alert-danger">
                                    {{ form.non_field_errors }}
                                </div>
                            {% endif %}
                            
                            <button type="submit" class="btn btn-primary w-100">Criar Usuário</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

banco/templates/banco_g-conta_bancaria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conta Bancária</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card mt-5 shadow-sm">
                    <div class="card-header text-center bg-info text-white">
                        <h2>Informações da Conta Bancária</h2>
                    </div>
                    <div class="card-body">
                        {% if usuario %}
                            <h3 class="mb-4">Detalhes do Usuário</h3>
                            <ul class="list-group mb-4">
                                <li class="list-group-item"><strong>Usuário:</strong> {{ usuario.pessoa.username }}</li>
                                <li class="list-group-item"><strong>Saldo BRL:</strong> {{ usuario.saldo_BLR }} R$</li>
                                <li class="list-group-item"><strong>Saldo USD:</strong> {{ usuario.saldo_USD }} $</li>
                                <li class="list-group-item"><strong>Saldo EUR:</strong> {{ usuario.saldo_EUR }} €</li>
                                <li class="list-group-item"><strong>Saldo BTC:</strong> {{ usuario.saldo_BTC }} $</li>
                                <li class="list-group-item"><strong>Saldo ARS:</strong> {{ usuario.saldo_ARS }} $</li>
                            </ul>

                            <div class="d-flex justify-content-between">
                                <a href="{% url 'banco:delete_conta_bancaria' usuario.id %}" class="btn btn-danger">
                                    DELETAR
                                </a>
                                <a href="{% url 'banco:get_cotacao' %}" class="btn btn-outline-secondary btn-lg">
                                    VERIFICAR COTAÇÃO DE MOEDAS
                                </a>
                                <a href="{% url 'banco:update_conta_bancaria' usuario.id %}" class="btn btn-warning">
                                    TROCAR DADOS
                                </a>
                                
                            </div>
                        {% else %}
                            <p class="text-danger">Nenhuma informação de usuário disponível.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

banco/templates/banco_g-cotacao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cotação de Moedas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card mt-5 shadow-sm">
                    <div class="card-header text-center bg-warning text-dark">
                        <h2>Cotação de Moedas</h2>
                    </div>
                    <div class="card-body">
                        <form method="get" action="{{form_action}}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-warning w-100">Obter Cotação</button>
                        </form>
                        
                        {% if cotacao %}
                            <div class="mt-4">
                                <h3>Resultado da Cotação</h3>
                                <ul class="list-group">
                                    <li class="list-group-item"><strong>Moeda 1:</strong> {{ cotacao.moeda_1 }}</li>
                                    <li class="list-group-item"><strong>Moeda 2:</strong> {{ cotacao.moeda_2 }}</li>
                                    <li class="list-group-item"><strong>Nome das Moedas:</strong> {{ cotacao.conversao }}</li>
                                    <li class="list-group-item"><strong>Valor de Compra:</strong> {{ cotacao.valor_compra }}</li>
                                    <li class="list-group-item"><strong>Valor de Venda:</strong> {{ cotacao.valor_venda }}</li>
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

banco/templates/banco_u-conta_bancaria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação de Conta Bancária</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card mt-5 shadow-sm">
                    <div class="card-header text-center bg-primary text-white">
                        <h2>Criação de Conta Bancária</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ form_action }}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary w-100">Atualizar Conta Bancária</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

banco/templates/pagina_inicial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site Cotação</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card mt-5 shadow-sm">
                    <div class="card-header bg-primary text-white">
                        <h1 class="mb-0">Site Cotação</h1>
                    </div>
                    <div class="card-body">
                        <div class="d-grid gap-3">
                            <a href="{% url 'banco:create_user' %}" class="btn btn-outline-primary btn-lg">
                                Criar Usuário
                            </a>
                            <a href="{% url 'banco:get_cotacao' %}" class="btn btn-outline-secondary btn-lg">
                                Verificar Cotação de Moedas
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>